

export const LINE_VERDICT_STYLES = {
  MATCH: {
    bg: "bg-green-50",
    text: "text-green-800",
    border: "border-green-200",
    badge: "bg-green-100 text-green-800",
    dot: "bg-green-500",
    label: "Match",
  },
  MISMATCH: {
    bg: "bg-red-50",
    text: "text-red-800",
    border: "border-red-200",
    badge: "bg-red-100 text-red-800",
    dot: "bg-red-500",
    label: "Mismatch",
  },
  MISSING: {
    bg: "bg-orange-50",
    text: "text-orange-800",
    border: "border-orange-200",
    badge: "bg-orange-100 text-orange-800",
    dot: "bg-orange-500",
    label: "Missing",
  },
  EXTRA: {
    bg: "bg-purple-50",
    text: "text-purple-800",
    border: "border-purple-200",
    badge: "bg-purple-100 text-purple-800",
    dot: "bg-purple-500",
    label: "Extra",
  },
  LOW_CONFIDENCE: {
    bg: "bg-yellow-50",
    text: "text-yellow-800",
    border: "border-yellow-200",
    badge: "bg-yellow-100 text-yellow-800",
    dot: "bg-yellow-500",
    label: "Low Confidence",
  },
  PARTIAL_DATA: {
    bg: "bg-gray-50",
    text: "text-gray-700",
    border: "border-gray-200",
    badge: "bg-gray-100 text-gray-700",
    dot: "bg-gray-400",
    label: "Partial Data",
  },
  PARTIAL_MATCH: {
    bg: "bg-sky-50",
    text: "text-sky-800",
    border: "border-sky-200",
    badge: "bg-sky-100 text-sky-800",
    dot: "bg-sky-500",
    label: "Partial Match",
  },
};

export const GLOBAL_VERDICT_STYLES = {
  VALIDATED: {
    bg: "bg-green-600",
    text: "text-white",
    border: "border-green-700",
    icon: "✓",
    label: "Validated",
    description: "All line items match. Document set is compliant.",
  },
  PARTIAL: {
    bg: "bg-orange-500",
    text: "text-white",
    border: "border-orange-600",
    icon: "⚠",
    label: "Partial Match",
    description: "Some items are missing from delivery or invoice.",
  },
  REJECTED: {
    bg: "bg-red-600",
    text: "text-white",
    border: "border-red-700",
    icon: "✗",
    label: "Rejected",
    description: "Critical mismatches found. Manual review required.",
  },
  REVIEW: {
    bg: "bg-yellow-500",
    text: "text-white",
    border: "border-yellow-600",
    icon: "?",
    label: "Needs Review",
    description: "Low confidence extractions or extra items detected.",
  },
  INCOMPLETE: {
    bg: "bg-gray-500",
    text: "text-white",
    border: "border-gray-600",
    icon: "–",
    label: "Incomplete",
    description: "One or more document types are missing from the PDF.",
  },
  PENDING: {
    bg: "bg-blue-500",
    text: "text-white",
    border: "border-blue-600",
    icon: "…",
    label: "Processing",
    description: "Document is being processed.",
  },
};

export const JOB_STATUS_STYLES = {
  PENDING: { color: "text-gray-500", label: "Pending" },
  PROCESSING: { color: "text-blue-600", label: "Processing" },
  CLASSIFYING: { color: "text-blue-600", label: "Classifying pages" },
  EXTRACTING: { color: "text-blue-600", label: "Extracting data" },
  VALIDATING: { color: "text-blue-600", label: "Validating" },
  MATCHING: { color: "text-blue-600", label: "Matching documents" },
  COMPLETED: { color: "text-green-600", label: "Completed" },
  FAILED: { color: "text-red-600", label: "Failed" },
  REVIEW_REQUIRED: { color: "text-yellow-600", label: "Review Required" },
};